/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajout_Membre (void);
GtkWidget* create_Menu_login (void);
GtkWidget* create_gestion_admin (void);
GtkWidget* create_Login_users (void);
GtkWidget* create_Profil_membre (void);
GtkWidget* create_Ajout_equipement (void);
GtkWidget* create_profil_entraineur (void);
GtkWidget* create_ajout_cours (void);
GtkWidget* create_ajouter_centre (void);
GtkWidget* create_ajouter_entraineur (void);
GtkWidget* create_ajouter_event (void);
