/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestion_admin;
  GtkWidget *Ajout_equipement;
  GtkWidget *profil_entraineur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gestion_admin = create_gestion_admin ();
  gtk_widget_show (gestion_admin);
  Ajout_equipement = create_Ajout_equipement ();
  gtk_widget_show (Ajout_equipement);
  profil_entraineur=create_profil_entraineur ();
  gtk_widget_show (profil_entraineur);


  gtk_main ();
  return 0;
}

