/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include "interface.h"
#include "support.h"

int main (int argc, char *argv[])
{
    GtkWidget *Login_users;
    GtkWidget *inscription;
#ifdef ENABLE_NLS
    bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
    bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
    textdomain (GETTEXT_PACKAGE);
#endif

    gtk_set_locale ();
    gtk_init (&argc, &argv);

#ifdef PACKAGE_DATA_DIR
    add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
#else
    add_pixmap_directory ("../pixmaps");
    add_pixmap_directory (".");
#endif
    
    
    Login_users       = create_Login_users();
    inscription       = create_inscription();
    
    gtk_widget_show (Login_users);
    gtk_widget_show (inscription);
    gtk_main ();
    return 0;
}
