/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Ajout_Membre;
  GtkWidget *Menu_login;
  GtkWidget *gestion_admin;
  GtkWidget *Login_users;
  GtkWidget *Profil_membre;
  GtkWidget *Ajout_equipement;
  GtkWidget *profil_entraineur;
  GtkWidget *ajout_cours;
  GtkWidget *ajouter_centre;
  GtkWidget *ajouter_entraineur;
  GtkWidget *ajouter_event;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
   //Ajout_Membre = create_Ajout_Membre ();
   //gtk_widget_show (Ajout_Membre);
  Menu_login = create_Menu_login ();
  gtk_widget_show (Menu_login);
  gestion_admin = create_gestion_admin ();
  //gtk_widget_show (gestion_admin);
  Login_users = create_Login_users ();
  //gtk_widget_show (Login_users);
  Profil_membre = create_Profil_membre ();
  //gtk_widget_show (Profil_membre);
   //Ajout_equipement = create_Ajout_equipement ();
   //gtk_widget_show (Ajout_equipement);
  profil_entraineur = create_profil_entraineur ();
  //gtk_widget_show (profil_entraineur);

   //ajout_cours = create_ajout_cours ();
   //gtk_widget_show (ajout_cours);
   //ajouter_centre = create_ajouter_centre ();
   //gtk_widget_show (ajouter_centre);
  ajouter_entraineur = create_ajouter_entraineur ();
  //gtk_widget_show (ajouter_entraineur);
   //ajouter_event = create_ajouter_event ();
  //gtk_widget_show (ajouter_event);

  gtk_main ();
  return 0;
}

