/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>


#include "support.h"
#include "interface.h"
int
main (int argc, char *argv[])
{

  GtkWidget *Menu_login;
  GtkWidget *gestion_admin;
  GtkWidget *Login_users;
  GtkWidget *Profil_membre;
  GtkWidget *ajout_cours;
  //GtkWidget *window1;
  //GtkWidget *window2;
  //GtkWidget *window3;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  Menu_login = create_Menu_login ();
  gtk_widget_show (Menu_login);
  gestion_admin = create_gestion_admin ();
  gtk_widget_show (gestion_admin);
  Login_users = create_Login_users ();
  gtk_widget_show (Login_users);
  Profil_membre = create_Profil_membre ();
  gtk_widget_show (Profil_membre);
  ajout_cours = create_ajout_cours ();
  gtk_widget_show (ajout_cours);

  //window1 = create_window1 ();
  //gtk_widget_show (window1);
  //window2 = create_window2 ();
  //gtk_widget_show (window2);
  //window3 = create_window3 ();
  //gtk_widget_show (window3);
  

  gtk_main ();
  return 0;
}

